"""initial baseline

Revision ID: 41b033cfed1b
Revises: 
Create Date: 2026-04-21 16:26:29.054181+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41b033cfed1b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_settings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('approval_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pending_invoice_id', sa.String(length=36), nullable=False),
    sa.Column('token', sa.String(length=128), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_approval_tokens_pending_invoice_id'), 'approval_tokens', ['pending_invoice_id'], unique=False)
    op.create_table('billing',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('plan', sa.String(length=50), nullable=False),
    sa.Column('invoices_limit', sa.Integer(), nullable=False),
    sa.Column('invoices_used', sa.Integer(), nullable=False),
    sa.Column('is_trial', sa.Boolean(), nullable=False),
    sa.Column('trial_ends_at', sa.DateTime(), nullable=True),
    sa.Column('subscription_start', sa.DateTime(), nullable=True),
    sa.Column('subscription_end', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_user_id'), 'billing', ['user_id'], unique=True)
    op.create_table('companies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('eik', sa.String(length=20), nullable=False),
    sa.Column('vat_number', sa.String(length=20), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('mol', sa.String(length=255), nullable=False),
    sa.Column('drive_purchases_folder_id', sa.String(length=255), nullable=False),
    sa.Column('drive_purchases_folder_path', sa.Text(), nullable=False),
    sa.Column('drive_sales_folder_id', sa.String(length=255), nullable=False),
    sa.Column('drive_sales_folder_path', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_profile_id'), 'companies', ['profile_id'], unique=False)
    op.create_table('company_shares',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_profile_id', sa.String(length=36), nullable=False),
    sa.Column('owner_user_id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('company_eik', sa.String(length=20), nullable=False),
    sa.Column('shared_with_email', sa.String(length=255), nullable=False),
    sa.Column('shared_with_user_id', sa.String(length=36), nullable=False),
    sa.Column('can_upload', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_shares_company_id'), 'company_shares', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_shares_owner_profile_id'), 'company_shares', ['owner_profile_id'], unique=False)
    op.create_index(op.f('ix_company_shares_shared_with_email'), 'company_shares', ['shared_with_email'], unique=False)
    op.create_table('company_verifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_verifications_company_id'), 'company_verifications', ['company_id'], unique=False)
    op.create_table('contact_inquiries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drive_links',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('folder_type', sa.String(length=50), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('drive_file_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drive_links_profile_id'), 'drive_links', ['profile_id'], unique=False)
    op.create_table('duplicate_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('keep_ids', sa.Text(), nullable=False),
    sa.Column('remove_ids', sa.Text(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_duplicate_requests_profile_id'), 'duplicate_requests', ['profile_id'], unique=False)
    op.create_table('inv_clients',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('eik', sa.String(length=20), nullable=True),
    sa.Column('egn', sa.String(length=20), nullable=True),
    sa.Column('vat_number', sa.String(length=20), nullable=True),
    sa.Column('is_vat_registered', sa.Boolean(), nullable=False),
    sa.Column('is_individual', sa.Boolean(), nullable=False),
    sa.Column('mol', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inv_clients_company_id'), 'inv_clients', ['company_id'], unique=False)
    op.create_index(op.f('ix_inv_clients_eik'), 'inv_clients', ['eik'], unique=False)
    op.create_index(op.f('ix_inv_clients_profile_id'), 'inv_clients', ['profile_id'], unique=False)
    op.create_table('inv_company_settings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('iban', sa.String(length=50), nullable=True),
    sa.Column('bank_name', sa.String(length=255), nullable=True),
    sa.Column('bic', sa.String(length=20), nullable=True),
    sa.Column('default_vat_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inv_company_settings_company_id'), 'inv_company_settings', ['company_id'], unique=True)
    op.create_table('inv_invoice_lines',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('invoice_id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inv_invoice_lines_invoice_id'), 'inv_invoice_lines', ['invoice_id'], unique=False)
    op.create_table('inv_invoice_meta',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('invoice_id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=True),
    sa.Column('document_type', sa.String(length=20), nullable=False),
    sa.Column('invoice_number', sa.Integer(), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('tax_event_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('vat_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('no_vat', sa.Boolean(), nullable=False),
    sa.Column('no_vat_reason', sa.Text(), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('pdf_path', sa.Text(), nullable=True),
    sa.Column('sync_status', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('cross_copy_status', sa.String(length=30), nullable=False),
    sa.Column('source_invoice_id', sa.String(length=36), nullable=False),
    sa.Column('composed_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_id')
    )
    op.create_index(op.f('ix_inv_invoice_meta_company_id'), 'inv_invoice_meta', ['company_id'], unique=False)
    op.create_index(op.f('ix_inv_invoice_meta_profile_id'), 'inv_invoice_meta', ['profile_id'], unique=False)
    op.create_table('inv_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('default_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inv_items_company_id'), 'inv_items', ['company_id'], unique=False)
    op.create_index(op.f('ix_inv_items_profile_id'), 'inv_items', ['profile_id'], unique=False)
    op.create_table('inv_stubs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('start_number', sa.Integer(), nullable=False),
    sa.Column('end_number', sa.Integer(), nullable=False),
    sa.Column('next_number', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inv_stubs_company_id'), 'inv_stubs', ['company_id'], unique=False)
    op.create_table('inv_sync_settings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('sync_mode', sa.String(length=20), nullable=False),
    sa.Column('delay_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inv_sync_settings_company_id'), 'inv_sync_settings', ['company_id'], unique=True)
    op.create_table('invoice_email_links',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('invoice_id', sa.String(length=36), nullable=False),
    sa.Column('token', sa.String(length=128), nullable=False),
    sa.Column('recipient_email', sa.String(length=255), nullable=False),
    sa.Column('pdf_path', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_invoice_email_links_invoice_id'), 'invoice_email_links', ['invoice_id'], unique=False)
    op.create_table('invoice_monthly_usage',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'year', 'month')
    )
    op.create_index(op.f('ix_invoice_monthly_usage_user_id'), 'invoice_monthly_usage', ['user_id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('new_filename', sa.String(length=500), nullable=False),
    sa.Column('invoice_type', sa.String(length=20), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('date', sa.String(length=20), nullable=False),
    sa.Column('issuer_name', sa.String(length=255), nullable=False),
    sa.Column('issuer_eik', sa.String(length=20), nullable=False),
    sa.Column('issuer_vat', sa.String(length=20), nullable=False),
    sa.Column('recipient_name', sa.String(length=255), nullable=False),
    sa.Column('recipient_eik', sa.String(length=20), nullable=False),
    sa.Column('recipient_vat', sa.String(length=20), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('total_amount', sa.String(length=50), nullable=False),
    sa.Column('vat_amount', sa.String(length=50), nullable=False),
    sa.Column('destination_path', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('cross_copy_status', sa.String(length=30), nullable=False),
    sa.Column('cross_copied_from', sa.String(length=255), nullable=False),
    sa.Column('source_invoice_id', sa.String(length=36), nullable=False),
    sa.Column('is_credit_note', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_profile_id'), 'invoices', ['profile_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_profile_id'), 'notifications', ['profile_id'], unique=False)
    op.create_table('pending_invoices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('new_filename', sa.String(length=500), nullable=False),
    sa.Column('invoice_type', sa.String(length=20), nullable=False),
    sa.Column('date', sa.String(length=20), nullable=False),
    sa.Column('issuer_name', sa.String(length=255), nullable=False),
    sa.Column('recipient_name', sa.String(length=255), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('pending_path', sa.Text(), nullable=False),
    sa.Column('source_profile_id', sa.String(length=36), nullable=False),
    sa.Column('source_invoice_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_invoices_profile_id'), 'pending_invoices', ['profile_id'], unique=False)
    op.create_table('profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('token', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('tos_consents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=False),
    sa.Column('consent_type', sa.String(length=50), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tos_consents_email'), 'tos_consents', ['email'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tos_consents_email'), table_name='tos_consents')
    op.drop_table('tos_consents')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_pending_invoices_profile_id'), table_name='pending_invoices')
    op.drop_table('pending_invoices')
    op.drop_index(op.f('ix_notifications_profile_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_invoices_profile_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_invoice_monthly_usage_user_id'), table_name='invoice_monthly_usage')
    op.drop_table('invoice_monthly_usage')
    op.drop_index(op.f('ix_invoice_email_links_invoice_id'), table_name='invoice_email_links')
    op.drop_table('invoice_email_links')
    op.drop_index(op.f('ix_inv_sync_settings_company_id'), table_name='inv_sync_settings')
    op.drop_table('inv_sync_settings')
    op.drop_index(op.f('ix_inv_stubs_company_id'), table_name='inv_stubs')
    op.drop_table('inv_stubs')
    op.drop_index(op.f('ix_inv_items_profile_id'), table_name='inv_items')
    op.drop_index(op.f('ix_inv_items_company_id'), table_name='inv_items')
    op.drop_table('inv_items')
    op.drop_index(op.f('ix_inv_invoice_meta_profile_id'), table_name='inv_invoice_meta')
    op.drop_index(op.f('ix_inv_invoice_meta_company_id'), table_name='inv_invoice_meta')
    op.drop_table('inv_invoice_meta')
    op.drop_index(op.f('ix_inv_invoice_lines_invoice_id'), table_name='inv_invoice_lines')
    op.drop_table('inv_invoice_lines')
    op.drop_index(op.f('ix_inv_company_settings_company_id'), table_name='inv_company_settings')
    op.drop_table('inv_company_settings')
    op.drop_index(op.f('ix_inv_clients_profile_id'), table_name='inv_clients')
    op.drop_index(op.f('ix_inv_clients_eik'), table_name='inv_clients')
    op.drop_index(op.f('ix_inv_clients_company_id'), table_name='inv_clients')
    op.drop_table('inv_clients')
    op.drop_index(op.f('ix_duplicate_requests_profile_id'), table_name='duplicate_requests')
    op.drop_table('duplicate_requests')
    op.drop_index(op.f('ix_drive_links_profile_id'), table_name='drive_links')
    op.drop_table('drive_links')
    op.drop_table('contact_inquiries')
    op.drop_index(op.f('ix_company_verifications_company_id'), table_name='company_verifications')
    op.drop_table('company_verifications')
    op.drop_index(op.f('ix_company_shares_shared_with_email'), table_name='company_shares')
    op.drop_index(op.f('ix_company_shares_owner_profile_id'), table_name='company_shares')
    op.drop_index(op.f('ix_company_shares_company_id'), table_name='company_shares')
    op.drop_table('company_shares')
    op.drop_index(op.f('ix_companies_profile_id'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_billing_user_id'), table_name='billing')
    op.drop_table('billing')
    op.drop_index(op.f('ix_approval_tokens_pending_invoice_id'), table_name='approval_tokens')
    op.drop_table('approval_tokens')
    op.drop_table('admin_settings')
    # ### end Alembic commands ###
